### Plot the results of the non-linear test

#' Plot the Results of the Non-linear Test
#'
#' Creates a contour plot of the region of the third-order moment outside the
#' test limits generated by [nonlintest()].
#'
#' @param x a `nonlintest` object produced by [nonlintest()].
#' @param plot display plot (TRUE) or return plot (FALSE)
#' @param \dots additional arguments to [plot()]
#' @returns ggplot Contour plot of the region of the third-order moment outside the
#'   test limits generated by [nonlintest()].
#' @author Adrian Barnett \email{a.barnett@qut.edu.au}
#' @seealso [nonlintest()]
#' @export
#' @examples
#' \donttest{
#'   test.res <- nonlintest(data=CVD$cvd, n.lag=4, n.boot=1000)
#'   plot(test.res)
#' }
plot.nonlintest <- function(x, plot = TRUE, ...) {
  z <- NULL # Setting some variables to NULL first (for R CMD check)

  ## Check
  if (!inherits(x, "nonlintest")) {
    stop("Object must be of class 'nonlintest'")
  }

  if (max(abs(x$region)) == 0) {
    cat('No points of the third-order moment exceed the test limits\n')
  }

  # Plot (only points that exceed limits)
  if (max(abs(x$region)) != 0) {
    counter <- 0
    for (r in 0:x$n.lag) {
      for (s in r:x$n.lag) {
        frame <- data.frame(r = r, s = s, z = x$region[r + 1, s + 1])
        if (counter == 0) {
          for.plot <- frame
        } else {
          for.plot <- rbind(for.plot, frame)
        }
        counter <- counter + 1
      }
    }

    gplot <- ggplot2::ggplot(for.plot, ggplot2::aes(r, s, z = z)) +
      ggplot2::geom_tile(ggplot2::aes(fill = z)) +
      ggplot2::stat_contour() +
      if (!plot) {
        return(invisible(gplot))
      }
    if (plot) {
      print(gplot)
    }
    #zlab='Area outside the test limits', ...)
    # mtext(side=3,'Points of 3rd order moment that exceed limits');
  } # end of if
} # end of function
