### Plot the results of the non-linear test

#' Plot the Results of the Non-linear Test
#'
#' `r lifecycle::badge("deprecated")` Soft-deprecated in favour of
#' [autoplot.nonlintest()], which returns a ggplot object you can extend
#' with `+`. The base R-style plot below still works.
#'
#' @param x a `nonlintest` object produced by [nonlintest()].
#' @param plot `r lifecycle::badge("deprecated")` display plot (TRUE) or
#'   return plot (FALSE).
#' @param \dots additional arguments to [plot()]
#' @returns ggplot Contour plot of the region of the third-order moment outside
#'   the test limits generated by [nonlintest()].
#' @author Adrian Barnett \email{a.barnett@qut.edu.au}
#' @seealso [autoplot.nonlintest()], [nonlintest()]
#' @export
#' @examples
#' \donttest{
#' test_res <- nonlintest(data = CVD$cvd, n.lag = 4, n.boot = 1000)
#' # Recommended:
#' autoplot(test_res)
#' # Still works, but deprecated:
#' plot(test_res)
#' }
plot.nonlintest <- function(x, plot = lifecycle::deprecated(), ...) {
  lifecycle::deprecate_warn(
    when = "0.3.17",
    what = "plot.nonlintest()",
    details = c(
      "Use `autoplot()` for a ggplot object you can extend:",
      i = "  autoplot(x) + ggplot2::theme_bw()"
    )
  )
  if (lifecycle::is_present(plot)) {
    lifecycle::deprecate_warn(
      when = "0.3.17",
      what = "plot.nonlintest(plot)",
      details = "Assign the return value of `autoplot(x)` instead."
    )
  } else {
    plot <- TRUE
  }

  check_if_nonlintest(x)
  # Setting some variables to NULL first (for R CMD check)
  z <- NULL

  if (max(abs(x$region)) == 0) {
    cli::cli_inform(
      "No points of the third-order moment exceed the test limits."
    )
    return(
      invisible(NULL)
    )
  }

  # Plot (only points that exceed limits)
  counter <- 0
  for (r in 0:x$n.lag) {
    for (s in r:x$n.lag) {
      frame <- data.frame(r = r, s = s, z = x$region[r + 1, s + 1])
      if (counter == 0) {
        for.plot <- frame
      } else {
        for.plot <- rbind(for.plot, frame)
      }
      counter <- counter + 1
    }
  }

  gplot <- ggplot2::ggplot(
    for.plot,
    ggplot2::aes(
      x = r,
      y = s,
      z = z
    )
  ) +
    ggplot2::geom_tile(ggplot2::aes(fill = z)) +
    ggplot2::stat_contour()
  if (!plot) {
    return(invisible(gplot))
  }
  print(gplot)
  invisible(gplot)
}

#' Plot the region of the third-order moment outside the test limits
#'
#' Returns a ggplot contour plot of the third-order moment region that
#' exceeds the bootstrap test limits computed by [nonlintest()]. Returns
#' `NULL` invisibly with an informational message if no points exceed
#' the limits.
#'
#' @param object a `nonlintest` object produced by [nonlintest()].
#' @param ... unused, for S3 generic compatibility.
#' @returns a ggplot contour plot, or `NULL` invisibly when no points
#'   exceed the test limits.
#' @author Nicholas Tierney
#' @seealso [nonlintest()]
#' @examples
#' \donttest{
#' \dontrun{
#' test_res <- nonlintest(data = CVD$cvd, n.lag = 4, n.boot = 1000)
#' autoplot(test_res)
#' }
#' }
#' @export
autoplot.nonlintest <- function(object, ...) {
  s <- r <- NULL
  check_if_nonlintest(object)
  z <- NULL
  if (max(abs(object$region)) == 0) {
    cli::cli_inform(
      "No points of the third-order moment exceed the test limits."
    )
    return(invisible(NULL))
  }
  coords <- expand.grid(r = 0:object$n.lag, s = 0:object$n.lag) |>
    subset(subset = s >= r)
  for_plot <- data.frame(
    r = coords$r,
    s = coords$s,
    z = object$region[cbind(coords$r + 1, coords$s + 1)]
  )
  ggplot2::ggplot(
    for_plot,
    ggplot2::aes(
      x = r,
      y = s,
      z = z
    )
  ) +
    ggplot2::geom_tile(ggplot2::aes(fill = z)) +
    ggplot2::stat_contour()
}
